// DojoGreeting.idl : DojoGreeting の IDL ソース
//

// このファイルは、タイプ ライブラリ (DojoGreeting.tlb) およびマーシャリング コードを
// 作成するために MIDL ツールによって処理されます。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(A1A496C5-C96D-4487-B219-9D5700391384),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IGreeting : IDispatch{
	[id(1)] HRESULT SayHello([out, retval] BSTR* pBstr);
};
[
	uuid(9FC8DCBC-F451-4936-82D0-A04E7AC770DD),
	version(1.0),
	helpstring("ComDojo Greeting Library 1.0")
]
library DojoGreetingLib
{
	importlib("stdole2.tlb");
	[
		uuid(A845A6FB-B1D5-4D59-AF48-5983D37B07B0)		
	]
	coclass Greeting
	{
		[default] interface IGreeting;
	};
};

